//Auth
export const MODIFY_EMAIL = 'modify_email'
export const MODIFY_PASSOWRD = 'modify_password'
export const MODIFY_NAME = 'modify_name'
export const REGISTER_SUCCESS = 'register_success'
export const REGISTER_ERROR = 'register_error'
export const REGISTER_IN_PROGRESS = 'register_in_progress'
export const LOGIN_SUCCESS = 'login_success'
export const LOGIN_ERROR = 'login_error'
export const LOGIN_IN_PROGRESS = 'login_in_progress'